name: GitHub Actions Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Executing SSH commands..."
            cd /home/ubuntu/Django_email_tracker
            git stash
            git branch
            git pull https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/aais-ai-2/backend.git dev
            git status
            sudo systemctl restart nginx
            sudo systemctl status nginx
            sudo systemctl restart gunicorn
            sudo systemctl status gunicorn
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

      - name: Show SSH command output
        if: always()  # Always run this step, even if the previous step fails
        run: |
          echo "SSH Command Output:"
          echo "${{ steps.ssh_deploy.outputs.stdout }}"
          echo "End of SSH Command Output"
          
          
        #    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
               # git pull https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/aais-ai-2/backend.git dev
